# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mb_subsystem/mb_subsystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem || ORIG_REF_NAME==mb_subsystem} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_periph_0/mb_subsystem_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_xlconcat_0/mb_subsystem_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mdm_1_0 || ORIG_REF_NAME==mb_subsystem_mdm_1_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_1_0/mb_subsystem_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_1_0 || ORIG_REF_NAME==mb_subsystem_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_rst_clk_wiz_1_100M_0/mb_subsystem_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_subsystem_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==mb_subsystem_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_xbar_0/mb_subsystem_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_xbar_0 || ORIG_REF_NAME==mb_subsystem_xbar_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_v10_0 || ORIG_REF_NAME==mb_subsystem_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_0/mb_subsystem_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_v10_0 || ORIG_REF_NAME==mb_subsystem_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_dlmb_bram_if_cntlr_0/mb_subsystem_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_subsystem_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_ilmb_bram_if_cntlr_0/mb_subsystem_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_subsystem_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_lmb_bram_0/mb_subsystem_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_lmb_bram_0 || ORIG_REF_NAME==mb_subsystem_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_reg_core_0_0/mb_subsystem_reg_core_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_reg_core_0_0 || ORIG_REF_NAME==mb_subsystem_reg_core_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_xlconstant_0_0/mb_subsystem_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_xlconstant_0_0 || ORIG_REF_NAME==mb_subsystem_xlconstant_0_0} -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0_ooc_debug.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_mdm_1_0 || ORIG_REF_NAME==mb_subsystem_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0_ooc_trace.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_1_0/mb_subsystem_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_1_0 || ORIG_REF_NAME==mb_subsystem_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_1_0/mb_subsystem_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_1_0 || ORIG_REF_NAME==mb_subsystem_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_1_0/mb_subsystem_clk_wiz_1_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_rst_clk_wiz_1_100M_0/mb_subsystem_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_subsystem_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_rst_clk_wiz_1_100M_0/mb_subsystem_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_subsystem_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_rst_clk_wiz_1_100M_0/mb_subsystem_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==mb_subsystem_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==mb_subsystem_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_xbar_0/mb_subsystem_xbar_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_v10_0 || ORIG_REF_NAME==mb_subsystem_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_0/mb_subsystem_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_v10_0 || ORIG_REF_NAME==mb_subsystem_ilmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_0/mb_subsystem_ilmb_v10_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_dlmb_bram_if_cntlr_0/mb_subsystem_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_ilmb_bram_if_cntlr_0/mb_subsystem_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_lmb_bram_0/mb_subsystem_lmb_bram_0_ooc.xdc

# XDC: bd/mb_subsystem/mb_subsystem_ooc.xdc
